---
title: "Municipalities"
output: html_document
date: "2024-04-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
```


```{r}
Fertilitetsrater_komune_alder <- read_csv("Fertilitetsrater_land_alder.csv")


#Fjern mellemrum
Fertilitetsrater_komune_alder <- Fertilitetsrater_komune_alder %>%
  rename(Samlet_fertilitet = `Samlet fertilitet`)

#kolonne municipalities
Fertilitetsrater_komune_alder <- Fertilitetsrater_komune_alder %>%
  rename(municipalities = ...1)

```


```{r}
Fertilitetsrater_komune_alder$fertilitetsrate <- round((Fertilitetsrater_komune_alder$Samlet_fertilitet / 1000), 1)
```

```{r}
municipalities_economy <- read_csv("municipalities_economy.csv")
municipalities_economy <- municipalities_economy %>%
  rename(municipalities = City)

Population <- read.csv("Population1.csv")
Fertility <- read.csv("Fertility.csv")

Population <- Population %>%
  rename(municipalities = X)

fertility <- merge(Fertilitetsrater_komune_alder, municipalities_economy, by = "municipalities", all = FALSE)
fertility2 <- merge(Fertility, Population, by = "municipalities", all = FALSE)

# subset
fertility2 <- fertility2[, c("municipalities", "fertilitetsrate", "econ_score", "Percent")]
write.csv(fertility2, "Fertility_clean.csv")
```

```{r}
quantile(municipalities_economy$Price, probs = , na.rm = FALSE)


#  0%     25%     50%     75%    100% 
#1276600 1575325 1804400 2099425 7413700 


#Make a score of economy
thresholds <- c(-Inf, 1575325,2099425 , Inf)
scores <- c(1, 2, 3)

# Create a new column to store the scores
fertility$econ_score <- cut(fertility$Price, breaks = thresholds, labels = scores)
fertility$econ_score <- as.numeric(fertility$econ_score)

# Inspect
score_counts <- table(fertility$econ_score)

# Plot pie chart
pie(score_counts, 
    main = "Pie Chart of Econ Scores",
    col = rainbow(length(score_counts)),
    labels = paste(names(score_counts), ": ", score_counts))

# Add a legend
legend("topright", 
       legend = names(score_counts), 
       fill = rainbow(length(score_counts)),
       title = "Econ Scores")


#Scatterplot
municipality_indices <- seq_along(fertility$municipalities)
plot(municipality_indices, 
     fertility$fertilitetsrate,
     xlab = "Municipalities",
     ylab = "fertility",
     main = "Scatterplot of Fertility Rate by Economic Group",
     col = fertility$econ_score)
```

```{r}
write_csv(fertility, "fertility.csv"
)
```



