---
title: "SocCult"
output: html_document
date: "2024-05-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
df <- read.csv("agents_data_40y.csv")
df2 <- read.csv("agents_data_40y2.csv")
df_mat <- read.csv("agents_data.csv")
df_cashbonus <- read.csv("data_w_cashbonus.csv")
```

```{r}
df_cashbenefit <- read.csv("data_w_cashbenefit.csv")

table(df_mat$Children)
table(df_cashbonus$Children)
table(df_cashbenefit$Children)

```

```{r}
# Make a column with all year_* columns summed
df$year_sum <- rowSums(df[, grepl("Year_", names(df))])
df2$year_sum <- rowSums(df2[, grepl("Year_", names(df2))])

# Print the min and max of the year_sum column
print(paste("Min:", min(df$year_sum)))
print(paste("Max:", max(df$year_sum)))

print(paste("Min:", min(df2$year_sum)))
print(paste("Max:", max(df2$year_sum)))

print(paste("Min:", min(df_mat$Children)))
print(paste("Max:", max(df_mat$Children)))

# count the number of occurrences of each value in the year_sum column
table(df$year_sum)
table(df2$year_sum)
table(df_mat$Children)


```
```{r}
#Count the TFR - so the total number of children diveded by the rows        
TFR <- sum(df_mat$Children) / nrow(df_mat)
print(TFR)

sum(df_mat$Children)
nrow(df_mat)
mean(df_mat$Children)

TFR <- sum(df_cashbonus$Children) / nrow(df_cashbonus)
print(TFR)

sum(df_cashbonus$Children)
nrow(df_cashbonus)
mean(df_cashbonus$Children)

```

```{r}
#Print the average and quantiles of number of children born in each socio_economic_class
df_cashbenefit %>%
    group_by(socio_economic_class) %>%
    summarise(mean_children = mean(Children),
              quantile_25 = quantile(Children, 0.25),
              quantile_75 = quantile(Children, 0.75))

TFR <- sum(df_cashbenefit$Children) / nrow(df_cashbenefit)
print(TFR)
```

```{r}
library(ggplot2)
#Plot the number of children from each socio_economic_class
df_mat$socio_economic_class <- as.factor(df_mat$socio_economic_class)
ggplot(df_mat, aes(x = socio_economic_class, y = Children)) + geom_boxplot()

df_cashbonus$socio_economic_class <- as.factor(df_cashbonus$socio_economic_class)
ggplot(df_cashbonus, aes(x = socio_economic_class, y = Children)) + geom_boxplot()

df_cashbenefit$socio_economic_class <- as.factor(df_cashbenefit$socio_economic_class)
ggplot(df_cashbenefit, aes(x = socio_economic_class, y = Children)) + geom_boxplot()



```

```{r}
print(colnames(df_cashbenefit))
```

```{r}
library(tidyr)
library(dplyr)

# Rename the columns to remove hyphens
df_cashbenefit <- df_cashbenefit %>%
  rename(
    "1519" = `X15.19`,
    "2024" = `X20.24`,
    "2529" = `X25.29`,
    "3034" = `X30.34`,
    "3539" = `X35.39`,
    "4044" = `X40.44`,
    "4549" = `X45.49`)
  
````

```{r}
# Reshape the data to long format
df_long <- pivot_longer(df_cashbenefit, 
                        cols = c("1519", "2024", "2529", "3034", "3539", "4044", "4549"),
                        names_to = "Age_Group", values_to = "Number_of_Children")
df_expanded <- df_long %>%
  uncount(Number_of_Children)

# Convert 'socio_economic_class' to factor
df_expanded$socio_economic_class <- as.factor(df_expanded$socio_economic_class)

# Print df_expanded to ensure it's created correctly
print(head(df_expanded))
````

```{r}
library(scales)

ggplot(df_expanded, aes(x = socio_economic_class, fill = Age_Group)) +
  geom_bar(position = "dodge") +
  labs(x = "Socio-economic Class", y = "Number of Children", fill = "Age Group") +
    labs(subtitle = "Number of Children Born in Each Age Group in Each Socio-economic Class",
    title = "Cash benefit pro natal policy") +  theme_minimal()

# Plot the percentage of children in each socio_economic_class in each age group
ggplot(df_expanded, aes(x = socio_economic_class, fill = Age_Group)) +
    geom_bar(position = "fill") +
    # Add labels of percentage of children of each age group in each socio-economic class
  geom_text(stat = "count", aes(label = scales::percent(..count../tapply(..count.., ..x.., sum)[..x..])),
            position = position_fill(vjust = 0.5)) + 
               labs(x = "Socio-economic Class", y = "Percentage of Children", fill = "Age Group") +
    labs(subtitle = "Percentage of Children Born in Each Age Group in Each Socio-economic Class",
    title = "Cash benefit pro natal policy") +
    theme_minimal()


  #Print the number agents in each socio_economic_class
table(df_expanded$socio_economic_class)
table(df_long$socio_economic_class)
```

```{r}
library(dplyr)
library(ggplot2)

# Calculate percentages
df_percentage <- df_expanded %>%
  group_by(socio_economic_class) %>%
  mutate(total_children_socio = sum(Children)) %>%
  group_by(socio_economic_class, Age_Group) %>%
  summarise(percentage = sum(Children) / first(total_children_socio) * 100) %>%
  ungroup()

# Plot the percentage of children in each socio-economic class in each age group
ggplot(df_percentage, aes(x = socio_economic_class, y = percentage, fill = Age_Group)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "Socio-economic Class", y = "Percentage of Children", fill = "Age Group") +
  labs(subtitle = "Percentage of Children Born in Each Age Group in Each Socio-economic Class",
       title = "Cash benefit pro natal policy") +
  theme_minimal()

```

```{r}
print(df_percentage)
```